spring.application.name=demo
spring.datasource.url=jdbc:postgresql://db:5432/travel_db
spring.datasource.username=user
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true